// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whvnvgzfdipawqwfcaqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indodm52Z3pmZGlwYXdxd2ZjYXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNjgzMTEsImV4cCI6MjA2MDk0NDMxMX0.ijHUjh8AMCkiNS-FqotP1AEugWgCXWRk0DHxzCkRUmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);